In [3]:
import numpy as np
a=np.arange (0,65534)
a.shape=(151,434)
print (a)

[[    0     1     2 ...   431   432   433]
 [  434   435   436 ...   865   866   867]
 [  868   869   870 ...  1299  1300  1301]
 ...
 [64232 64233 64234 ... 64663 64664 64665]
 [64666 64667 64668 ... 65097 65098 65099]
 [65100 65101 65102 ... 65531 65532 65533]]


In [ ]:
x = [1,1,1,1,1,1,2,2,2,2,3,3,3,3,3,4,5,6,7,7,7,7,7,7,9,9,9,11,13,13,13,13,13,16,16,17,17]
y = [3,3,3,3,3,5,6,7,7,7,7,7,7,10,15,15,15,17,17,17,19,19,19,]
z = [13,13,13,13,13,13,13,13,13,13,13,13,13,17,17,18,18,18,18,18]
import matplotlib.pyplot as plt
plt.hist(x,y,z)
plt.show()